### ISSUE TITLE
transitive external configs are not loaded

### ISSUE THREAD

**Issue by davidcwalker** [sbglasius/external-config#42]
I have the following configuration block in my application.yml:
````
grails:
    config:
        locations:
            - classpath:envConfig.yml
````

The file envConfig.yml contains the following block:

````
test:
    grails:
        config:
            locations:
                - file:///path/to/file/dbConfig.yml
````

The dbConfig.yml file is not loaded, and so I am unable to use configuration values defined in it.
